# frozen_string_literal: true

require "feedjira"
require "twitter"
require "twitter-text"
require "http"
require "socket"
require "cgi"
require "rchardet"
require "addressable"
require "ostruct"

require "feedkit/core_ext/try"
require "feedkit/feedjira_extension"

require "feedkit/version"
require "feedkit/detect_encoding"
require "feedkit/errors"
require "feedkit/rebase"
require "feedkit/basic_auth"
require "feedkit/redirect"
require "feedkit/response"
require "feedkit/request"
require "feedkit/curl"
require "feedkit/twitter_url_recognizer"
require "feedkit/tweets"

require "feedkit/parser"
require "feedkit/parser/entry"
require "feedkit/parser/feed"
require "feedkit/parser/json_entry"
require "feedkit/parser/json_feed"
require "feedkit/parser/twitter_entry"
require "feedkit/parser/twitter_feed"
require "feedkit/parser/xml_entry"
require "feedkit/parser/xml_feed"
require "feedkit/parser/html_document"
